from pydantic import BaseModel, Field

class ChatResponseDTO(BaseModel):
    """DTO for chat responses from Gemini"""
    
    response: str = Field(..., description="Response generated by the model")
    
    class Config:
        json_schema_extra = {
            "example": {
                "response": "The capital of France is Paris."
            }
        } 