from abc import ABC, abstractmethod
from typing import Optional

class DialogSystemServiceInterface(ABC):
    """Interface for dialog system services that generate responses"""
    
    @abstractmethod
    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        context: Optional[str] = None
    ) -> str:
        """
        Generates a response based on system prompt, user prompt and optional context
        
        Args:
            system_prompt: Instructions on how the model should respond
            user_prompt: User's question or prompt
            context: Optional additional context for the conversation
            
        Returns:
            str: Response generated by the model
        """
        pass 